Simplify the logic and no longer chain credential manager

diff --git a/src/git-credential-1password b/src/git-credential-1password
--- a/src/git-credential-1password
+++ b/src/git-credential-1password
@@ -1,69 +1,59 @@
 #!/usr/bin/env bash
 
-if echo "protocol=https
-hosts=test
-username=test
-" | git credential-cache fill >/dev/null 2>&1; then
-  TOKEN_MANAGER=credential-cache
-else
-  TOKEN_MANAGER=credential-store
-fi
+account="$1"
+item_name="$2"
+git_credential_action="$3"
 
-function cache_op_session() {
-  ACCOUNT="$1"
-  TOKEN="$2"
+op_session_path="$HOME"/.opsession/$account
+mkdir -p "$HOME"/.opsession
+touch "$op_session_path"
+chmod 600 "$op_session_path"
 
-  echo "protocol=https
-host=$ACCOUNT
-username=$ACCOUNT
-password=$TOKEN
-" | git "$TOKEN_MANAGER" store
+op_session_varname=OP_SESSION_$account
+export "$op_session_varname"="$(cat "$op_session_path")"
+
+function handle_signin_response() {
+  if [[ -z ${!op_session_varname} ]]; then
+    echo '❌ Unable to login.'
+    exit 1
+  else
+    echo '✅ Login successful.'
+  fi
 }
 
-function get_op_session() {
-  ACCOUNT="$1"
-
-  echo "protocol=https
-host=$ACCOUNT
-username=$ACCOUNT
-" | git "$TOKEN_MANAGER" get | grep 'password=' | cut -d= -f2
-}
-
-function reset_op_session() {
-  ACCOUNT="$1"
-
-  echo "protocol=https
-host=$ACCOUNT
-username=$ACCOUNT
-" | git "$TOKEN_MANAGER" erase
+function auto_signin() {
+  echo '❓ Checking if there is an existing session.'
+  if [[ -z ${!op_session_varname} ]]; then
+    echo '❌ Cannot find an existing session. To log in again.'
+    export "$op_session_varname"="$(op signin "$account" --output=raw | tee "$op_session_path")"
+    handle_signin_response
+  else
+    echo '❓ Found an existing session. Checking if the session is still active.'
+    if ! op list vaults --account="$account" >/dev/null 2>&1; then
+      echo '❌ Session expired. To log in again.'
+      export "$op_session_varname"="$(op signin "$account" --output=raw | tee "$op_session_path")"
+      handle_signin_response
+    else
+      echo '✅ Found an existing and active session.'
+    fi
+  fi
 }
 
 function get_credential() {
-  ACCOUNT="$1"
-  NAME="$2"
+  credential=$(op get item "$item_name" --account="$account" --fields username,password,url --format json)
 
-  OP_SESSION="--account=$ACCOUNT --session=$(get_op_session "$ACCOUNT")"
+  ssh_user="$(echo "$credential" | jq -r .username)"
+  ssh_pass="$(echo "$credential" | jq -r .password)"
 
-  if ! op list vaults $OP_SESSION >/dev/null 2>&1; then
-    TOKEN="$(op signin "$ACCOUNT" --output=raw </dev/tty)"
-    cache_op_session "$ACCOUNT" "$TOKEN"
-    OP_SESSION="--account=$ACCOUNT --session=$(get_op_session "$ACCOUNT")"
-  fi
-
-  CREDENTIAL="$(op get item "$NAME" $OP_SESSION --fields username,password --format CSV)"
-
-  echo username="$(echo "$CREDENTIAL" | cut -d, -f1)"
-  echo password="$(echo "$CREDENTIAL" | cut -d, -f2)"
+  echo username="$ssh_user"
+  echo password="$ssh_pass"
 }
 
-case "$3" in
+case "$git_credential_action" in
 
 'get')
-  get_credential "$1" "$2"
-  ;;
-
-'erase')
-  reset_op_session "$1" "$2"
+  auto_signin
+  get_credential
   ;;
 
 esac
